name: Publish Template Package

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:
    inputs:
      publish_source:
        description: 'Package source URL used by dotnet nuget push.'
        required: true
        default: 'https://nuget.pkg.github.com/cdcavell/index.json'
