name: Publish Container

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

env:
  IMAGE_NAME: ghcr.io/cdcavell/netcoreapplicationtemplate
  LOCAL_IMAGE_NAME: netcoreapplicationtemplate-release
  TRIVY_IMAGE: aquasec/trivy:0.58.2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false