# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: GitHub Actions security analysis

on:
  # Manual trigger
  workflow_dispatch:

  # Every Sunday morning
  schedule:
    - cron: '15 9 * * 0'

  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/dependabot.yml'

# Deny all token permissions unless granted by a job.
permissions: {}

jobs:
  zizmor:
    name: Analyze workflows with zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          inputs: .
          online-audits: true
          persona: regular
          version: v1.26.1
          advanced-security: true

  actionlint:
    name: Validate workflows with actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: docker://rhysd/actionlint@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667 # v1.7.12
        with:
          args: -color
